### ISSUE TITLE
The WWW redirect to Non-WWW does not work anymore.

### ISSUE THREAD

**Issue by ronald2wing** [reliqarts/laravel-common#7]
**Describe the bug**
I see this error: `[2024-03-20 17:59:52] production.ERROR: Symfony\Component\HttpFoundation\Request::setTrustedProxies(): Argument #2 ($trustedHeaderSet) must be of type int, null given, called in /var/www/pop-creme/releases/9/vendor/reliqarts/laravel-common/src/Http/Middleware/NonWWW.php on line 20 {"exception":"[object] (TypeError(code: 0): Symfony\\Component\\HttpFoundation\\Request::setTrustedProxies(): Argument #2 ($trustedHeaderSet) must be of type int, null given, called in /var/www/pop-creme/releases/9/vendor/reliqarts/laravel-common/src/Http/Middleware/NonWWW.php on line 20 at /var/www/pop-creme/releases/9/vendor/symfony/http-foundation/Request.php:527)`

**To Reproduce**
1. Insteall the compose on clean
2. Add the NonWWW middleware to bootstrap/app.php
3. Go to www subdomain
4. Error because the config('trustedproxy.headers') is missing.

**Expected behavior**
It should redirect to non www without errors.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 121.0.6167.139 (Official Build) (64-bit)

**Comment by reliq** [comment]
Hi @ronald2wing, thank you for reporting this issue. 

What version of the package are you using?

**Comment by ronald2wing** [comment]
I am using v8.0.0

**Comment by ronald2wing** [comment]
Thank you!

**Comment by reliq** [comment]
No problem @ronald2wing. It should be fixed with [v8.0.1](https://github.com/reliqarts/laravel-common/releases/tag/v8.0.1).
